packages/lesswrong/styles/_comments.scss
Should fade to zero opacity, not to a color almost as dark as the text. Soon LW will rework the comment linking and obsolete the fix, but what can you do.
=> Non-awful colors for comment direct-link fade

packages/lesswrong/lib/routes.ts
This is a small correction to a page title. I show the mistake in the below screenshot of a Chrome tab.
=> Rename EAF Search page title so to not reference LW

packages/lesswrong/lib/routes.ts
The new Recommendations section has a link to /library in "Continue Reading". Make it redirect to /sequences.
=> Add library route to occupy link from new recommendation section

packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx, packages/lesswrong/components/tagging/AllTagsPage.tsx, packages/lesswrong/components/tagging/WikiGradeDisplay.tsx, packages/lesswrong/components/users/UsersProfile.tsx, packages/lesswrong/lib/betas.ts, packages/lesswrong/lib/collections/posts/views.ts, packages/lesswrong/lib/collections/users/recommendationSettings.ts, packages/lesswrong/server/migrations/migrationUtils.ts, packages/lesswrong/server/scripts/exportPostDetails.ts, yarn.lock
Some of these are just cleaning up small diffs that I stashed but didn't think were worth their own full PR, like the changes to migrationUtils.
For lack of a better time, in this PR I make the user pages have a meta description that's not just the generic site one.
I've disabled the progress bar completely. My guess is LW will comment out that line or delete it, at which point we'll no longer have the diff. However the wiki-grade feature is here to stay on LW, so I've made that change in such a way that I can submit upstream.
There may be some css changes coming, applied to the AllTags page through the eaThemes.ts file. That's blocked waiting on Aaron, but I thought I'd submit this now anyway.
=> Fixes after merge

packages/lesswrong/components/form-components/ImageUpload.tsx, packages/lesswrong/components/notifications/NotificationTypeSettings.tsx, packages/lesswrong/components/posts/PostsPage/PostsPage.tsx, packages/lesswrong/components/sequenceEditor/EditSequenceTitle.tsx, packages/lesswrong/lib/collections/posts/collection.ts, packages/lesswrong/lib/collections/posts/custom_fields.ts, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/collections/posts/helpers.ts, packages/lesswrong/lib/collections/posts/schema.ts, packages/lesswrong/lib/generated/databaseTypes.d.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts, packages/lesswrong/server/callbacks/postCallbacks.ts, packages/lesswrong/styles/_sequences.scss
Add a field to the Posts schema that stores the cloudinary ID of a user-uploaded image for the social media preview.
In Vulcan-style, we include in our schema that it should be controlled by the ImageUpload component. Annoyingly, most of the work in this otherwise-simple PR was fixing the styling.
While I was working on ImageUpload styling, I needed to both reference, and make sure I didn't break, the styling from the sequences edit page. And in doing so noticed some areas for improvement.
=> Add ability to set image for social media preview

packages/lesswrong/components/common/TabNavigationMenu/TabNavigationFooterItem.tsx
This applies the same fix I did in `TabNavigationItem`  to `TabNavigationFooterItem`.
@jpaddison3 I assume this is worthy of a hot fix but feel free to close if you disagree.
To test: make your browser window small enough that you see the menu as footer items, and then click on the EA hub link.
=> Hot fix:  Fix hub link in footer

packages/lesswrong/lib/routes.ts
Shows up as the title of the page on the browser tab. Currently it's using LW's term for the page.
=> Tiny title fix

packages/lesswrong/themes/eaTheme.ts
Now that headers are better about reporting their true size, it's not needed, and was causing an unwanted small grey background.
=> Remove header spacing override for Layout

packages/lesswrong/lib/collections/posts/schema.ts
Allow admins to edit the post setting `canonicalSource`, allowing them to set the `rel="canonical"` tags on linkposts that are not auto-posted through RSS.
=> Make canonicalSource admin-editable

packages/lesswrong/components/ea-forum/EAHome.tsx, packages/lesswrong/components/ea-forum/StickiedPosts.tsx, packages/lesswrong/components/posts/PostsItem2.tsx, packages/lesswrong/components/posts/PostsTitle.tsx, packages/lesswrong/lib/collections/posts/constants.ts, packages/lesswrong/lib/collections/posts/views.ts, packages/lesswrong/lib/components.ts, packages/lesswrong/themes/eaTheme.ts
This PR separates out Pinned Posts into their own section above Frontpage Posts on the home page. It also adds unique icons to all pinned open threads, pinned AMA posts, and the 'Start Here' post.
For a more easily reviewable list of changes (at least until the earlier commits from `lw-devel` are merged), see this PR: https://github.com/LessWrong2/Lesswrong2/pull/4075
=> Pinned Posts Section

packages/lesswrong/lib/collections/posts/schema.ts
Aaron uses this extensively. It's unfortunate that it's not a better user experience, but it's important that he can do it.
The capability to do so was (inadvertently?) removed in this PR: https://github.com/LessWrong2/Lesswrong2/pull/4093/files .
I've tested that the editing works.
=> Allow Admins to Edit Author ID

packages/lesswrong/server/migrations/2021-07-22-fixDuplicateEmails.ts, packages/lesswrong/server/scripts/fixDuplicateEmail.tests.ts, packages/lesswrong/server/scripts/fixDuplicateEmail.ts, packages/lesswrong/server/scripts/mergeAccounts.ts
Fix to #168
1. Recalculate karma after transferring votes, not before
2. set the destination user to be the user with something in the email address array, if one exists
3. Include users  where deleted is null, not just where it's false
We still have one user [who claimed](https://app.intercom.com/a/apps/xycbzvda/inbox/inbox/3705107/conversations/69456500011050) that their account was deactivated after running this script. Both Aaron and I think that their account is activated, and I'm confused what's happening here. I haven't received any response from them in a business week though, so I'm inclined to move ahead.
=> Duplicate email fix fix

packages/lesswrong/lib/routes.ts
This PR adds in a route for the EA Handbook, in the vein of the `/about` route.
=> Add EA Handbook Route

packages/lesswrong/components/Layout.tsx
User bans don't take effect except once a user has logged out. This PR adds a ban notice to the layout component for banned users, so the ban will take effect immediately.
=> [Hotfix] Ban logged-in users

package.json, packages/lesswrong/lib/collections/users/helpers.ts, packages/lesswrong/lib/publicSettings.ts, packages/lesswrong/server/callbacks/userCallbacks.ts, yarn.lock
This PR adds code to automatically subscribe users to the forum digest on signup (or whenever they toggle the `subscribedToDigest` field, which is also accessible in account settings). Unsubscribe is also supported. It also adds all new users to a new Mailchimp audience for a forthcoming drip campaign.
=> Forum Digest Subscription

packages/lesswrong/server/migrations/2021-08-13-postDefaultStickyPriority.ts, packages/lesswrong/server/migrations/index.ts
Posts without a set sticky priority get sorted below all other posts on the front page. This affects posts from before ~April 30th of this year. Aaron ran into this while trying to publish an old draft from a forum user, which he couldn't get  to show up on the front page.
This PR resolves this by filling in the default priority for all posts.
=> Post default sticky priority migration

packages/lesswrong/components/recentDiscussion/RecentDiscussionSubscribeReminder.tsx, packages/lesswrong/components/users/SignupSubscribeToCurated.tsx
This PR adds a small CTA capsule in the Recent Discussion feed. It's main purpose is to prompt signing up for the EA Forum weekly digest email (or the LW curated posts email depending on the forum type) if the user has not already done so. Logged out users will be prompted to create an account or login.
I generally feel like we can get rid of the "Maybe Later" button and compress the component to make it less obtrusive, but for the initial pass I wanted to focus on getting it working and not mess with the LW experience. (I did remove the "Maybe Later" button from the logged out view because it seemed pretty useless for that version.)
=> add a forum digest subscription reminder to the Recent Discussion feed

packages/lesswrong/components/posts/SubmitToFrontpageCheckbox.tsx, packages/lesswrong/lib/collections/posts/custom_fields.ts
Also avoid promoting posts where the author wants it to stay in personal
Unlike LW, we default posts to the frontpage by default and pull them out if they don't meet the bar. This meant we were:
1. Promoting events to the frontpage by default, cluttering the frontpage until a moderator removed it
2. Promoting posts that the author said they wanted to stay in personal (see screenshot)
Both of those are now fixed.
Also fix the wording, as we haven't had a Community section in a good while.
=> Don't promote events to frontpage by default

packages/lesswrong/components/Layout.tsx, packages/lesswrong/components/users/BannedNotice.tsx, packages/lesswrong/components/vulcan-forms/Form.tsx, packages/lesswrong/lib/collections/comments/tests.ts, packages/lesswrong/lib/vulcan-lib/errors.ts, packages/lesswrong/lib/vulcan-users/permissions.ts, packages/lesswrong/server/akismet.ts, packages/lesswrong/server/apolloServer.ts, packages/lesswrong/server/authenticationMiddlewares.ts, packages/lesswrong/server/callbacks.ts, packages/lesswrong/server/callbacks/commentCallbacks.ts
*Issue 1: If you get banned you can still login*
The proximate cause of the error is that express-session keeps you logged in. We remove your loginToken when you get banned, which would log you out, but now express session also has a cookie-based method to keep you logged in. Turns out we don't need to ask passport to use express-session to track logins, so I've removed it. It was silly to have the duplication. Upon doing so, I've removed the code that showed people the banned notice if they're logged in while being banned.
To restate / clarify:
Previously the state would be:
* DB:
* user.services.resume.loginTokens: 'asdf'
* sessions.something: 'zxvc'
* Client cookies: 
* loginToken: 'hjkl'
* connect.sid: 'nmop'
Now we only have the loginToken ones.
*Issue 2: Even if somehow logged-in, I …
=> Fix issues around post-ban spamming

packages/lesswrong/components/sequences/SequencesPage.tsx
Fixes [this issue](https://app.asana.com/0/628521446211730/1200805988361616/f).
Previously, anyone can view a draft sequence. Now, only people who have access to edit the sequence can view it.
=> dont show draft sequences to people who arent the author

packages/lesswrong/server.ts, packages/lesswrong/server/scripts/ensureEmailInEmails.ts
This script tries to ensure that users with an `email` also have that listed in their `emails` by appending it to the array if it's not already there and the `email` is not in a different user's `emails`.
=> add a script to clean up some user email data

packages/lesswrong/components/users/NewUserCompleteProfile.tsx, packages/lesswrong/server/resolvers/userResolvers.ts
The ways to sign up are:
* Auth0 email + password
* Auth0 google OAuth
* Auth0 facebook OAuth
Only Facebook allows for no email to be set, so I'm confident in that text.
I've checked that this doesn't change the flow if you do have an email.
I don't do any validation of the email address on the frontend, because this is only for .5 users every month, so I don't think it's worth it. I do check on the backend though. The error propagates sensibly if you submit a malformed email address.
=> Ask users from facebook without an email for their email

packages/lesswrong/components/localGroups/CommunityHome.tsx, packages/lesswrong/server/resolvers/recentDiscussionFeed.ts
This PR removes the word "beta" from the Groups/Events page, and it excludes newly created in-person events from the Recent Discussion section. A **comment** on an event will make it appear in Recent Discussion. Online events still appear in Recent Discussion.
=> Remove "beta" from Groups/Events page, and hide newly created in-person events in Recent Discussion

.github/CODEOWNERS, .github/CONTRIBUTING.md
This should make github assign a reviewer by default, so we don't have to remember.
=> Default reviewer

packages/lesswrong/components/common/TabNavigationMenu/EventsList.tsx, packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
LessWrong shows some upcoming nearby events in their home page sidebar, and here we are adding that section to the EA Forum sidebar as well. I also noticed that that section was not using the browser's location data (which the Groups/Events page does), so I updated the logic to match that in `CommunityHome.tsx`.
=> show upcoming nearby events on the main forum page sidebar

packages/lesswrong/components/posts/PostsAnalyticsPage.tsx
CreatedAt is APARENTLY an admin only field. I often test with non-admin users, but this feature was easier to test with admin users, so I didn't notice.
=> Fix data issue notes not showing up for non-admins

packages/lesswrong/components/ea-forum/FeaturedResourceBanner.tsx, packages/lesswrong/lib/collections/featuredResources/views.ts
We are randomly selecting a resource to show in the banner, but because we do server-side rendering there is the possibility that the server will randomly select a different resource than the client, causing problems. This PR wraps that selection inside of a `useEffect`, removing the problem.
I think the correct way to handle this is by having Mongo only return one resource selected at random, but Mongo only allows random selection in aggregation pipelines and Vulcan does not seem to allow aggregation pipelines in views. If someone knows that either of those statements are false, I would appreciate learning it.
Also, this has some whitespace changes. I tried to mess with my editor to avoid this but it wasn't immediately working and I figured it wasn't the best use of time since we aren't …
=> Featured resource fix

packages/lesswrong/lib/routes.ts
Add a redirect bc an email went out with the old path. See https://cea-core.slack.com/archives/CB5D60VSB/p1635847627047000
=> add redirect for old community path

packages/lesswrong/components/localGroups/EventTime.tsx, packages/lesswrong/components/localGroups/GroupLinks.tsx, packages/lesswrong/components/posts/PostsPage/PostsPageEventData.tsx, packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx, packages/lesswrong/lib/collections/posts/custom_fields.ts, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/generated/databaseTypes.d.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
We are already collecting external event page links (FB, Meetup, other site) for events, now we display them on the event page. I think most events will just have one of these three (but some will have multiple), so might look a little weird on its own line in practice - let me know if you have suggestions on where to put the icons.
I also fixed a small bug on the event page where we were not always showing the timezone.
=> display external event links on the event page
